production:
  username: adam
  adapter: postgresql
  host: localhost
  database: modernhippie_dev

development:
  username: adam
  adapter: postgresql
  host: localhost
  database: modernhippie_dev

test:
  username: adam
  adapter: postgresql
  host: localhost
  database: modernhippie_test
  min_messages: warning
